index:
  path: /
  controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::urlRedirectAction
  defaults:
    path: /home
    permanent: true

controllers:
  resource:
    path: ../src/Controller/
    namespace: App\Controller
  type: attribute
confirm_email:
  path: /confirm-email/{token}
  controller: App\Controller\SecurityController::confirmEmail
clubdetails:
  path: /club/{id}
  controller: App\Controller\ClubController::details
  methods: GET

joinclub:
  path: /club/{id}/join
  controller: App\Controller\ClubController::joinClub
  methods: GET
