services:
    _defaults:
        autowire: true      # Automatically injects dependencies based on type hints
        autoconfigure: true # Automatically tags services for common interfaces
    App\Service\:
        resource: '../src/Service'
    App\Controller\:
        resource: '../src/Controller' # Loads all controllers from the Controller directory
        tags: ['controller.service_arguments'] # Ensures that arguments for controller actions are resolved
    App\Repository\:
        resource: '../src/Repository' # Loads all repositories from the Repository directory
        tags: ['doctrine.repository_service'] # Ensures that repositories are tagged correctly
    App\Security\:
        resource: '../src/Security'
    App\Service\OpenAIClient:
        arguments:
            $apiKey:  '%env(OPENAI_API_KEY)%'
    App\Service\ToxicityDetector:
        arguments:
            $client: '@http_client'
            $apiKey: '%env(OPENAI_API_KEY)%'
